version: '3'
services:
  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service-container
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/auth-service-container"]
    networks:
      - backend-network

  main-service:
    build:
      context: ./backend/services/main-service
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      - db
    volumes:
      - ./images:/images
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/backend-container"]
    networks:
      - backend-network

  db:
    image: postgres:17.0
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data  
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin      
    ports:
      - "8082:80" 
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
