version: '3'
services:
  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service-container
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/auth-service-container"]
    networks:
      - backend-network
      
  feed-service:
    build:
      context: ./backend/services/feed-service
      dockerfile: Dockerfile
    container_name: feed-service-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8093:8093"
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/feed-service-container"]
    networks:
      - backend-network
  search-service:
    build:
      context: ./backend/services/search-service
      dockerfile: Dockerfile
    container_name: search-service-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8084:8084"
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/search-service-container"]
    networks:
      - backend-network
      
  profile-service:
    build:
      context: ./backend/services/profile-service
      dockerfile: Dockerfile
    container_name: profile-service-container
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/profile-service-container"]
    networks:
      - backend-network

  itinerary-service:
    build:
      context: ./backend/services/itinerary-service
      dockerfile: Dockerfile
    container_name: itinerary-service-container
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/itinerary-service-container"]
    networks:
      - backend-network

  save-service:
    build:
      context: ./backend/services/save-service
      dockerfile: Dockerfile
    container_name: save-service-container
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    command: ["/wait-for-it.sh", "db:5432", "--strict", "--", "/save-service-container"]
    networks:
      - backend-network

  main-service:
    build:
      context: ./backend/services/main-service
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

  db:
    image: postgres:17.0
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data  
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin      
    ports:
      - "8082:80" 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
