version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      - db
    command: sh -c "sleep 3; go run ./main-service/cmd/main.go"

  db:
    image: postgres:17.0
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin      
    ports:
      - "8082:80" 
    depends_on:
      - db

volumes:
  db_data:
